// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelZmodem() {
  return window['go']['main']['App']['CancelZmodem']();
}

export function ClearScreen() {
  return window['go']['main']['App']['ClearScreen']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetBBSList() {
  return window['go']['main']['App']['GetBBSList']();
}

export function GetCursor() {
  return window['go']['main']['App']['GetCursor']();
}

export function GetScreen() {
  return window['go']['main']['App']['GetScreen']();
}

export function GetScreenSnapshot() {
  return window['go']['main']['App']['GetScreenSnapshot']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsViewingLog() {
  return window['go']['main']['App']['IsViewingLog']();
}

export function LoadLog() {
  return window['go']['main']['App']['LoadLog']();
}

export function LogExit() {
  return window['go']['main']['App']['LogExit']();
}

export function LogNextPage() {
  return window['go']['main']['App']['LogNextPage']();
}

export function LogPrevPage() {
  return window['go']['main']['App']['LogPrevPage']();
}

export function SendCtrlKey(arg1) {
  return window['go']['main']['App']['SendCtrlKey'](arg1);
}

export function SendKey(arg1) {
  return window['go']['main']['App']['SendKey'](arg1);
}

export function SendSpecialKey(arg1) {
  return window['go']['main']['App']['SendSpecialKey'](arg1);
}

export function SendText(arg1) {
  return window['go']['main']['App']['SendText'](arg1);
}

export function UploadFile() {
  return window['go']['main']['App']['UploadFile']();
}
