// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearScreen():Promise<void>;

export function Connect(arg1:string,arg2:number,arg3:string):Promise<string>;

export function Disconnect():Promise<void>;

export function GetBBSList():Promise<Array<main.BBSEntry>>;

export function GetCursor():Promise<Record<string, number>>;

export function GetScreen():Promise<Array<any>>;

export function IsConnected():Promise<boolean>;

export function IsViewingLog():Promise<boolean>;

export function LoadLog():Promise<string>;

export function LogExit():Promise<void>;

export function LogNextPage():Promise<void>;

export function LogPrevPage():Promise<void>;

export function SendCtrlKey(arg1:string):Promise<void>;

export function SendKey(arg1:Array<number>):Promise<void>;

export function SendSpecialKey(arg1:string):Promise<void>;

export function SendText(arg1:string):Promise<void>;

export function UploadFile():Promise<string>;
